### ISSUE TITLE
Duplicate checklist item: Child independence

### ISSUE THREAD

**Issue by LeaVerou** [webcomponents/gold-standard#18]
https://github.com/webcomponents/gold-standard/wiki/Parent-Child-Independence
https://github.com/webcomponents/gold-standard/wiki/Child-Independence

It looks like the latter is a less elaborate version of the former? Even the example is almost the same.

**Comment by JanMiksovsky** [comment]
Good catch — many thanks! Embarrassed to say that that's been there for years, and no one's mentioned it before.

I removed the second of the two pages after moving a bit of its content into the first page. Since it felt more like a Content topic, I put the remaining page under the Content heading.

(I also noticed that, since the last edits to the wiki, GitHub appears to have changed its markdown-to-HTML formatting, causing some links to break, so fixed those as well.)
